### ISSUE TITLE
include "tensorflow/lite/core/interpreter.h should be include "tensorflow/lite/interpreter.h

### ISSUE THREAD

**Issue by StuartIanNaylor** [usefulsensors/openai-whisper#16]
Slightly confused as built this earlier but trying now and getting #include "tensorflow/lite/core/interpreter.h doesn't exist
when I look its not in core but #include "tensorflow/lite/interpreter.h

**Comment by nyadla-sys** [comment]
@StuartIanNaylor are you trying to build on Linux machine ?
and have you followed below steps
https://github.com/usefulsensors/openai-whisper#run-whisper-inference-on-tflite-framework

**Comment by StuartIanNaylor** [comment]
Yeah that is what is confusing me as it did run before but when I clone tensorflow now its definately tensorflow/lite/interpreter.h and confused how it worked before.
Oh its only the latest edition now I look that has it in core if your clone a branch it doesn't exist
