### ISSUE TITLE
ERROR: Model provided has model identifier 'ion ', should be 'TFL3'

### ISSUE THREAD

**Issue by MMM-Jasmin** [usefulsensors/openai-whisper#41]
Hi,
i just tried to execute the minimal example, but i run into the following error:

`bash> ./minimal ../models/whisper-small.tflite ../samples/jfk.wav

n_vocab:50257

mel.n_len3000

mel.n_mel:80
ERROR: Model provided has model identifier 'ion ', should be 'TFL3'

Error at ~/openai-whisper/tensorflow_src/tensorflow/lite/examples/minimal/minimal.cc:179`

**Comment by MMM-Jasmin** [comment]
upsi... forgott the git lfs.. sorry

**Comment by JingliangGao** [comment]
OK, I got this. I have  run the command 'git lfs install' before glone this repo, and it is succeed. Thinks~
