### ISSUE TITLE
30 seconds limit

### ISSUE THREAD

**Issue by narakai** [usefulsensors/openai-whisper#43]
Thanks for the great work. It seems that the record time limit is 30 seconds. Is it possible to set a longer time?

**Comment by nyadla-sys** [comment]
Segmenting the audio into 30-second blocks and performing inference on each block is both feasible and it needs to be worked on ...

**Comment by narakai** [comment]
Thanks for the reply, just want to process a .wav file which > 30 seconds instead of recoding a voice, will try to use ffmpeg to  segment the file first.
